So_Long: srcs/clean_images.c File Reference
clean_images.c File Reference
#include "so_long.h"
Functions
static void cleanup_collect_anims (t_game *game)
static void cleanup_floor_images (t_game *game)
static void cleanup_player_anims (t_game *game)
static void cleanup_player_left_anims (t_game *game)
void cleanup_scaled_images (t_game *game)
Function Documentation
cleanup_collect_anims()
static void cleanup_collect_anims (t_game * game) static
Definition at line 73 of file clean_images.c.
{
    int i;
    i = 0;
    while (i < 8)
    {
        if (game->collect[i])
        {
            mlx_destroy_image(game->mlx, game->collect[i]);
            game->collect[i] = NULL;
        }
        i++;
    }
}
Referenced by cleanup_scaled_images().
cleanup_floor_images()
static void cleanup_floor_images (t_game * game) static
Definition at line 15 of file clean_images.c.
{
    int i;
    i = 0;
    while (i < 10)
    {
        if (game->floor[i])
        {
            mlx_destroy_image(game->mlx, game->floor[i]);
            game->floor[i] = NULL;
        }
        i++;
    }
}
Referenced by cleanup_scaled_images().
cleanup_player_anims()
static void cleanup_player_anims (t_game * game) static
Definition at line 31 of file clean_images.c.
{
    int i;
    i = 0;
    while (i < 6)
    {
        if (game->player_idle[i])
        {
            mlx_destroy_image(game->mlx, game->player_idle[i]);
            game->player_idle[i] = NULL;
        }
        if (game->player_run[i])
        {
            mlx_destroy_image(game->mlx, game->player_run[i]);
            game->player_run[i] = NULL;
        }
        i++;
    }
}
Referenced by cleanup_scaled_images().
cleanup_player_left_anims()
static void cleanup_player_left_anims (t_game * game) static
Definition at line 52 of file clean_images.c.
{
    int i;
    i = 0;
    while (i < 6)
    {
        if (game->player_idle_left[i])
        {
            mlx_destroy_image(game->mlx, game->player_idle_left[i]);
            game->player_idle_left[i] = NULL;
        }
        if (game->player_run_left[i])
        {
            mlx_destroy_image(game->mlx, game->player_run_left[i]);
            game->player_run_left[i] = NULL;
        }
        i++;
    }
}
Referenced by cleanup_scaled_images().
cleanup_scaled_images()
void cleanup_scaled_images (t_game * game)
Definition at line 89 of file clean_images.c.
{
    cleanup_floor_images(game);
    cleanup_player_anims(game);
    cleanup_player_left_anims(game);
    cleanup_collect_anims(game);
}
References cleanup_collect_anims(), cleanup_floor_images(), cleanup_player_anims(), and cleanup_player_left_anims().
Referenced by cleanup_mlx_images().