So_Long: srcs/ft_snprintf.c File Reference
ft_snprintf.c File Reference
#include "so_long.h"
Functions
static void ft_itoa_to_buf (int n, char *str, int *pos, size_t size)
int ft_snprintf (char *str, size_t size, const char *format,...)
Custom implementation of snprintf for integer and string conversion.
static void ft_strncpy_buf (const char *src, char *str, int *pos, size_t size)
Function Documentation
ft_itoa_to_buf()
static void ft_itoa_to_buf (int n, char * str, int * pos, size_t size) static
Definition at line 15 of file ft_snprintf.c.
{
    long num;
    char digits[12]; // Enough for 32-bit int
    int i = 0;
    num = n;
    if (num < 0)
    {
        if (*pos < (int)size - 1)
            str[(*pos)++] = '-';
        num = -num;
    }
    // Handle 0 specially
    if (num == 0)
    {
        if (*pos < (int)size - 1)
            str[(*pos)++] = '0';
        return;
    }
    // Convert to digits in reverse order
    while (num > 0)
    {
        digits[i++] = '0' + (num % 10);
        num /= 10;
    }
    // Copy digits in correct order
    while (i > 0 && *pos < (int)size - 1)
        str[(*pos)++] = digits[--i];
}
Referenced by ft_snprintf().
ft_snprintf()
int ft_snprintf (char * str, size_t size, const char * format, ...)
Custom implementation of snprintf for integer and string conversion.
Parameters
str Output buffer
size Buffer size
format Format string (supports d and s)
... Variable arguments
Returns
Number of characters written (excluding null terminator)
Definition at line 63 of file ft_snprintf.c.
{
    va_list args;
    int pos;
    if (!str || !format || size == 0)
        return (0);
    va_start(args, format);
    pos = 0;
    while (*format && pos < (int)size - 1)
    {
        if (*format == '%')
        {
            format++;
            if (*format == 'd')
                ft_itoa_to_buf(va_arg(args, int), str, &pos, size);
            else if (*format == 's')
                ft_strncpy_buf(va_arg(args, char *), str, &pos, size);
            format++;
        }
        else
            str[pos++] = *format++;
    }
    str[pos] = '\0';
    va_end(args);
    return (pos);
}
References ft_itoa_to_buf(), and ft_strncpy_buf().
Referenced by load_sprite_array(), and render_frame().
ft_strncpy_buf()
static void ft_strncpy_buf (const char * src, char * str, int * pos, size_t size) static
Definition at line 49 of file ft_snprintf.c.
{
    while (src && *src && *pos < (int)size - 1)
        str[(*pos)++] = *src++;
}
Referenced by ft_snprintf().