So_Long: srcs/image_operations.c File Reference
image_operations.c File Reference
#include "so_long.h"
Functions
static void * create_scaled_image (void *mlx, int n_size)
void * flip_image_horizontal (void *mlx, void *img)
Creates a horizontally flipped copy of an image.
void flip_sprites (t_game *game)
Creates left-facing versions of all player sprites.
static void process_scaling (int *new_data, int *orig_data, int *p, int width)
void * scale_image (void *mlx, void *original, int width, int height)
Function Documentation
create_scaled_image()
static void * create_scaled_image (void * mlx, int n_size) static
Examples
/home/mkurkar/CoreProjects/so_long/srcs/image_operations.c.
Definition at line 20 of file image_operations.c.
{
    void    *new_img;
    new_img = mlx_new_image(mlx, n_size, n_size);
    return (new_img);
}
Referenced by scale_image().
flip_image_horizontal()
void * flip_image_horizontal (void * mlx, void * img)
Creates a horizontally flipped copy of an image.
Parameters
mlx MLX instance pointer
img Source image to flip
Returns
void* Pointer to the new flipped image
Creates a new image that is a mirror of the input image. Used for creating left-facing sprites from right-facing ones. Maintains transparency information.
Examples
/home/mkurkar/CoreProjects/so_long/srcs/image_operations.c.
Definition at line 147 of file image_operations.c.
{
    int     width;
    int     height;
    int     params[3];
    void    *new_img;
    char    *data[2];
    width = 32;
    height = 32;
    new_img = mlx_new_image(mlx, width, height);
    data[0] = mlx_get_data_addr(new_img, &params[0], &params[1], &params[2]);
    data[1] = mlx_get_data_addr(img, &params[0], &params[1], &params[2]);
    params[0] = -1;
    while (++params[0] < height)
    {
        params[2] = -1;
        while (++params[2] < width)
        {
            *(unsigned int *)(data[0] + params[0] * params[1] + (width - 1
                        - params[2]) * 4) = *(unsigned int *)(data[1]
                    + params[0] * params[1] + params[2] * 4);
        }
    }
    return (new_img);
}
Referenced by flip_sprites().
flip_sprites()
void flip_sprites (t_game * game)
Creates left-facing versions of all player sprites.
Parameters
game Pointer to game structure
Creates mirrored versions of both idle and running animations for the player character. These are used when the player is moving or facing left.
Examples
/home/mkurkar/CoreProjects/so_long/srcs/image_operations.c, and /home/mkurkar/CoreProjects/so_long/srcs/init_main.c.
Definition at line 183 of file image_operations.c.
{
    int i;
    i = 0;
    while (i < 6)
    {
        game->player_idle_left[i] = flip_image_horizontal(game->mlx,
                game->player_idle[i]);
        game->player_run_left[i] = flip_image_horizontal(game->mlx,
                game->player_run[i]);
        i++;
    }
}
References flip_image_horizontal().
Referenced by init_game().
process_scaling()
static void process_scaling (int * new_data, int * orig_data, int * p, int width) static
Examples
/home/mkurkar/CoreProjects/so_long/srcs/image_operations.c.
Definition at line 55 of file image_operations.c.
{
    int i;
    int j;
    int n_size;
    i = -1;
    n_size = 32;
    while (++i < n_size)
    {
        j = -1;
        while (++j < n_size)
        {
            if (i * width / n_size * width + j * width / n_size >= 0
                && i * width / n_size * width + j * width / n_size
                < (width * p[4]))
                new_data[i * n_size + j] = orig_data[i * width / n_size
                    * width + j * width / n_size];
        }
    }
}
Referenced by scale_image().
scale_image()
void * scale_image (void * mlx, void * original, int width, int height)
Examples
/home/mkurkar/CoreProjects/so_long/srcs/image_operations.c.
Definition at line 107 of file image_operations.c.
{
    void    *new_img;
    int     *orig_data;
    int     *new_data;
    int     params[5];
    new_img = create_scaled_image(mlx, 32);
    if (!new_img)
        return (NULL);
    orig_data = (int *)mlx_get_data_addr(original, &params[0], &params[1],
            &params[2]);
    if (!orig_data)
    {
        mlx_destroy_image(mlx, new_img);
        return (NULL);
    }
    new_data = (int *)mlx_get_data_addr(new_img, &params[0], &params[1],
            &params[2]);
    if (!new_data)
    {
        mlx_destroy_image(mlx, new_img);
        return (NULL);
    }
    params[4] = height;
    process_scaling(new_data, orig_data, params, width);
    return (new_img);
}
References create_scaled_image(), and process_scaling().
Referenced by load_single_texture(), and load_sprite_array().