So_Long: srcs/init_main.c File Reference
init_main.c File Reference
#include "so_long.h"
Functions
void init_game (t_game *game, char *map_path)
Main game initialization function.
static void init_game_vars (t_game *game)
void init_game_window (t_game *game)
static void init_mlx_and_map (t_game *game, char *map_path)
Function Documentation
init_game()
void init_game (t_game * game, char * map_path)
Main game initialization function.
Parameters
game Pointer to game structure
map_path Path to the map file
Initialization sequence:
Reset game state
Initialize MLX
Load map
Create window
Load assets
Initialize player and collectibles
Set up event hooks
Examples
/home/mkurkar/CoreProjects/so_long/srcs/init_main.c.
Definition at line 123 of file init_main.c.
{
    init_game_vars(game);
    init_mlx_and_map(game, map_path);
    init_game_window(game);
    init_buffer(game);
    load_assets(game);
    flip_sprites(game);
    init_player_position(game);
    init_collectibles(game);
    mlx_hook(game->win, 2, 1L << 0, key_hook, game);
    mlx_hook(game->win, 12, 0, expose_hook, game);
    mlx_loop_hook(game->mlx, animate, game);
}
References animate(), expose_hook(), flip_sprites(), init_buffer(), init_collectibles(), init_game_vars(), init_game_window(), init_mlx_and_map(), init_player_position(), key_hook(), and load_assets().
Referenced by main().
init_game_vars()
static void init_game_vars (t_game * game) static
Examples
/home/mkurkar/CoreProjects/so_long/srcs/init_main.c.
Definition at line 15 of file init_main.c.
{
    ft_memset(game, 0, sizeof(t_game));
    game->frame = 0;
    game->is_running = 0;
    game->tile_size = 32;
    game->facing_right = 1;
    game->moves_count = 0;
    game->run_counter = 0;
}
Referenced by init_game().
init_game_window()
void init_game_window (t_game * game)
Examples
/home/mkurkar/CoreProjects/so_long/srcs/init_main.c.
Definition at line 52 of file init_main.c.
{
    int win_width;
    int win_height;
    win_width = game->map_width * game->tile_size;
    win_height = game->map_height * game->tile_size;
    game->win = mlx_new_window(game->mlx, win_width, win_height, "so_long");
    if (!game->win)
    {
        cleanup_game(game);
        ft_printf("Error: Failed to create window\n");
        exit(1);
    }
}
References cleanup_game().
Referenced by init_game().
init_mlx_and_map()
static void init_mlx_and_map (t_game * game, char * map_path) static
Examples
/home/mkurkar/CoreProjects/so_long/srcs/init_main.c.
Definition at line 89 of file init_main.c.
{
    ft_printf("Initializing MLX...\n");
    game->mlx = mlx_init();
    if (!game->mlx)
    {
        cleanup_game(game);
        ft_printf("Error: MLX initialization failed\n");
        exit(1);
    }
    ft_printf("Reading map: %s\n", map_path);
    game->map = read_map(map_path, &game->map_width, &game->map_height);
    if (!game->map || !validate_map(game))
    {
        ft_printf("Error: Invalid map: %s\n", map_path);
        cleanup_game(game);
        exit(1);
    }
}
References cleanup_game(), read_map(), and validate_map().
Referenced by init_game().