So_Long: srcs/init.c File Reference
init.c File Reference
#include "../includes/so_long.h"
Functions
void init_collectibles (t_game *game)
Initializes collectible items and exit.
void init_floor_types (t_game *game)
Initializes random floor tile variations.
void init_game (t_game *game, char *map_path)
Main game initialization function.
static void init_game_vars (t_game *game)
static void init_game_window (t_game *game)
static void init_mlx_and_map (t_game *game, char *map_path)
void init_player_position (t_game *game)
Locates and sets the player's starting position.
Function Documentation
init_collectibles()
void init_collectibles (t_game * game)
Initializes collectible items and exit.
Parameters
game Pointer to game structure
Counts total collectibles ('C' in map)
Locates exit position ('E' in map)
Initializes completion tracking
Definition at line 72 of file init.c.
{
    int i;
    int j;
    i = 0;
    game->collectibles_count = 0;
    while (game->map[i])
    {
        j = 0;
        while (game->map[i][j])
        {
            if (game->map[i][j] == 'C')
                game->collectibles_count++;
            else if (game->map[i][j] == 'E')
            {
                game->exit_x = j;
                game->exit_y = i;
            }
            j++;
        }
        i++;
    }
    game->can_exit = 0;
}
Referenced by init_game().
init_floor_types()
void init_floor_types (t_game * game)
Initializes random floor tile variations.
Parameters
game Pointer to game structure
Creates a 2D array of floor type indices. Each position gets a random floor variant (0-9) for visual variety in the game.
Definition at line 12 of file init.c.
{
    int i;
    int j;
    i = 0;
    game->floor_types = (unsigned char **)malloc(sizeof(unsigned char *) * game->map_height);
    while (i < game->map_height)
    {
        j = 0;
        game->floor_types[i] = (unsigned char *)malloc(sizeof(unsigned char) * game->map_width);
        while (j < game->map_width)
        {
            game->floor_types[i][j] = (unsigned char)(rand() % 10);
            j++;
        }
        i++;
    }
}
Referenced by load_assets().
init_game()
void init_game (t_game * game, char * map_path)
Main game initialization function.
Parameters
game Pointer to game structure
map_path Path to the map file
Initialization sequence:
Reset game state
Initialize MLX
Load map
Create window
Load assets
Initialize player and collectibles
Set up event hooks
Definition at line 160 of file init.c.
{
    init_game_vars(game);
    init_mlx_and_map(game, map_path);
    init_game_window(game);
    init_buffer(game);
    load_assets(game);
    flip_sprites(game);
    init_player_position(game);
    init_collectibles(game);
    mlx_hook(game->win, 2, 1L << 0, key_hook, game);
    mlx_hook(game->win, 12, 0, expose_hook, game);
    mlx_loop_hook(game->mlx, animate, game);
}
References animate(), expose_hook(), flip_sprites(), init_buffer(), init_collectibles(), init_game_vars(), init_game_window(), init_mlx_and_map(), init_player_position(), key_hook(), and load_assets().
Referenced by main().
init_game_vars()
static void init_game_vars (t_game * game) static
Definition at line 115 of file init.c.
{
    ft_memset(game, 0, sizeof(t_game));
    game->frame = 0;
    game->is_running = 0;
    game->tile_size = 32;
    game->facing_right = 1;
    game->moves_count = 0;
    game->run_counter = 0;
}
Referenced by init_game().
init_game_window()
static void init_game_window (t_game * game) static
Definition at line 98 of file init.c.
{
    int win_width;
    int win_height;
    win_width = game->map_width * game->tile_size;
    win_height = game->map_height * game->tile_size;
    game->win = mlx_new_window(game->mlx, win_width, win_height, "so_long");
    if (!game->win)
    {
        cleanup_game(game); // Add cleanup before error
        ft_printf("Error: Failed to create window\n");
        exit(1);
    }
}
References cleanup_game().
Referenced by init_game().
init_mlx_and_map()
static void init_mlx_and_map (t_game * game, char * map_path) static
Definition at line 126 of file init.c.
{
    ft_printf("Initializing MLX...\n");
    game->mlx = mlx_init();
    if (!game->mlx)
    {
        cleanup_game(game);
        ft_printf("Error: MLX initialization failed\n");
        exit(1);
    }
    ft_printf("Reading map: %s\n", map_path);
    game->map = read_map(map_path, &game->map_width, &game->map_height);
    if (!game->map || !validate_map(game))
    {
        ft_printf("Error: Invalid map: %s\n", map_path);
        cleanup_game(game);
        exit(1);
    }
}
References cleanup_game(), read_map(), and validate_map().
Referenced by init_game().
init_player_position()
void init_player_position (t_game * game)
Locates and sets the player's starting position.
Parameters
game Pointer to game structure
Scans the map for 'P' character and sets player_x and player_y coordinates accordingly.
Definition at line 40 of file init.c.
{
    int i;
    int j;
    i = 0;
    while (game->map[i])
    {
        j = 0;
        while (game->map[i][j])
        {
            if (game->map[i][j] == 'P')
            {
                game->player_x = j;
                game->player_y = i;
                return;
            }
            j++;
        }
        i++;
    }
}
Referenced by init_game().