So_Long: srcs/load.c File Reference
load.c File Reference
#include "so_long.h"
Functions
void load_assets (t_game *game)
Loads all game assets from files.
static void load_single_texture (t_game *game, void **dest, char *path)
void load_sprite_array (t_game *game, void **arr, char *base_path, int frames)
Loads a sequence of sprite frames from files.
Function Documentation
load_assets()
void load_assets (t_game * game)
Loads all game assets from files.
Parameters
game Pointer to game structure
Loads and initializes:
Floor tiles (10 variants)
Player animations (idle and running)
Collectible items
Wall textures
Exit texture All textures are scaled to match tile_size (32x32)
Examples
/home/mkurkar/CoreProjects/so_long/srcs/init_main.c.
Definition at line 82 of file load.c.
{
    game->tile_size = 32;
    game->img_width = game->tile_size;
    game->img_height = game->tile_size;
    ft_printf("Loading assets...\n");
    load_sprite_array(game, game->floor, "./final_assets/floor", 10);
    load_sprite_array(game, game->player_idle, "./final_assets/idle_knigh",
        6);
    load_sprite_array(game, game->player_run, "./final_assets/run_knight",
        6);
    load_sprite_array(game, game->collect, "./final_assets/chest", 8);
    load_single_texture(game, &game->wall, "./final_assets/wall/f1.xpm");
    load_single_texture(game, &game->exit, "./final_assets/exit.xpm");
    init_floor_types(game);
    ft_printf("All assets loaded successfully!\n");
}
References init_floor_types(), load_single_texture(), and load_sprite_array().
Referenced by init_game().
load_single_texture()
static void load_single_texture (t_game * game, void ** dest, char * path) static
Definition at line 49 of file load.c.
{
    void    *orig_img;
    orig_img = mlx_xpm_file_to_image(game->mlx, path, &game->img_width,
            &game->img_height);
    if (!orig_img)
    {
        ft_printf("Error: Failed to load texture: %s\n", path);
        exit(1);
    }
    *dest = scale_image(game->mlx, orig_img, game->img_width, game->img_height);
    mlx_destroy_image(game->mlx, orig_img);
    if (!*dest)
    {
        ft_printf("Error: Failed to scale texture: %s\n", path);
        exit(1);
    }
}
References scale_image().
Referenced by load_assets().
load_sprite_array()
void load_sprite_array (t_game * game, void ** arr, char * base_path, int frames)
Loads a sequence of sprite frames from files.
Parameters
mlx MLX instance pointer
arr Array to store the loaded sprites
base_path Base path to the sprite files
frames Number of frames to load
Loads a sequence of XPM files named f0.xpm through f{frames-1}.xpm from the specified directory. Each sprite is scaled to 32x32 pixels.
Definition at line 26 of file load.c.
{
    char    path[256];
    void    *orig_img;
    void    *scaled_img;
    int     params[3];
    int     i;
    i = 0;
    while (i < frames)
    {
        ft_snprintf(path, sizeof(path), "%s/f%d.xpm", base_path, i);
        orig_img = mlx_xpm_file_to_image(game->mlx, path, &params[0], &params[1]);
        if (!orig_img)
            handle_error(game, "Failed to load sprite");
        scaled_img = scale_image(game->mlx, orig_img, params[0], params[1]);
        mlx_destroy_image(game->mlx, orig_img);
        if (!scaled_img)
            handle_error(game, "Failed to scale image");
        arr[i++] = scaled_img;
    }
}
References ft_snprintf(), handle_error(), and scale_image().
Referenced by load_assets().