So_Long: srcs/main.c File Reference
main.c File Reference
#include "so_long.h"
Functions
int close_window (t_game *game)
static void exit_game (t_game *game)
int main (int argc, char **argv)
Function Documentation
close_window()
int close_window (t_game * game)
Definition at line 9 of file main.c.
{
    exit_game(game);
    return (0);
}
References exit_game().
Referenced by main().
exit_game()
static void exit_game (t_game * game) static
Definition at line 3 of file main.c.
{
    cleanup_game(game);
    exit(0);
}
References cleanup_game().
Referenced by close_window().
main()
int main (int argc, char ** argv)
Definition at line 15 of file main.c.
{
    t_game game;
    if (argc != 2)
    {
        ft_printf("Error: Usage: %s <map_path.ber>\n", argv[0]);
        return (1);
    }
    // Check if file ends with .ber
    char *dot = ft_strrchr(argv[1], '.');
    if (!dot || strcmp(dot, ".ber") != 0)
    {
        ft_printf("Error: Map file must have .ber extension\n");
        return (1);
    }
    ft_memset(&game, 0, sizeof(t_game)); // Initialize to zero
    init_game(&game, argv[1]);
    ft_printf("Starting game loop...\n");
    // Add window close hook
    mlx_hook(game.win, 17, 0, close_window, &game);
    if (game.mlx && game.win)
    {
        render_frame(&game);
        mlx_loop(game.mlx);
    }
    else
    {
        handle_error(&game, "Failed to initialize game");
    }
    return (0);
}
References close_window(), handle_error(), init_game(), and render_frame().