So_Long: srcs/map_validations_utils.c File Reference
map_validations_utils.c File Reference
#include "so_long.h"
Functions
int check_elements (t_game *game, int i, int j, t_counts *count)
int check_map_borders (t_game *game)
Simple map validation check for basic requirements.
int check_map_content (t_game *game, t_counts *count)
int validate_counts (t_game *game, t_counts count)
Function Documentation
check_elements()
int check_elements (t_game * game, int i, int j, t_counts * count)
Definition at line 33 of file map_validations_utils.c.
{
    char    c;
    c = game->map[i][j];
    if (c == 'P')
    {
        count->player++;
        game->player_x = j;
        game->player_y = i;
    }
    else if (c == 'E')
    {
        count->exit++;
        game->exit_x = j;
        game->exit_y = i;
    }
    else if (c == 'C')
        count->collect++;
    else if (c != '0' && c != '1')
        return (ft_printf("Error: Invalid character in map\n") && 0);
    return (1);
}
References s_counts::collect, s_counts::exit, and s_counts::player.
Referenced by check_map_content().
check_map_borders()
int check_map_borders (t_game * game)
Simple map validation check for basic requirements.
Parameters
game Pointer to game structure
Returns
int 1 if valid, 0 if invalid
Examples
/home/mkurkar/CoreProjects/so_long/srcs/map_validation.c.
Definition at line 20 of file map_validations_utils.c.
{
    int j;
    if (game->map_height < 3 || game->map_width < 3)
        return (ft_printf("Error: Map too small\n") && 0);
    j = -1;
    while (++j < game->map_width)
        if (game->map[0][j] != '1' || game->map[game->map_height - 1][j] != '1')
            return (ft_printf("Error: Map not surrounded by walls\n") && 0);
    return (1);
}
Referenced by validate_map().
check_map_content()
int check_map_content (t_game * game, t_counts * count)
Examples
/home/mkurkar/CoreProjects/so_long/srcs/map_validation.c.
Definition at line 57 of file map_validations_utils.c.
{
    int i;
    int j;
    i = -1;
    while (++i < game->map_height)
    {
        if ((int)ft_strlen(game->map[i]) != game->map_width)
            return (ft_printf("Error: Map not rectangular\n") && 0);
        if (game->map[i][0] != '1' || game->map[i][game->map_width - 1] != '1')
            return (ft_printf("Error: Map not surrounded by walls\n") && 0);
        j = -1;
        while (++j < game->map_width)
            if (!check_elements(game, i, j, count))
                return (0);
    }
    return (1);
}
References check_elements().
Referenced by validate_map().
validate_counts()
int validate_counts (t_game * game, t_counts count)
Examples
/home/mkurkar/CoreProjects/so_long/srcs/map_validation.c.
Definition at line 77 of file map_validations_utils.c.
{
    if (count.player != 1)
        return (ft_printf("Error: Must have exactly one player\n") && 0);
    if (count.exit != 1)
        return (ft_printf("Error: Must have exactly one exit\n") && 0);
    if (count.collect < 1)
        return (ft_printf("Error: Must have at least one collectible\n") && 0);
    game->collectibles_count = count.collect;
    return (1);
}
References s_counts::collect, s_counts::exit, and s_counts::player.
Referenced by validate_map().