So_Long: srcs/map.c File Reference
map.c File Reference
#include "so_long.h"
Functions
static char ** allocate_map (char *file, int *height)
static void clean_newline (char *line)
char ** read_map (char *file, int *width, int *height)
Reads and parses the game map from a file.
static int validate_width (char **lines, int i, int width)
Function Documentation
allocate_map()
static char ** allocate_map (char * file, int * height) static
Definition at line 24 of file map.c.
{
    int     fd;
    char    *line;
    char    **lines;
    fd = open(file, O_RDONLY);
    if (fd < 0)
        return (NULL);
    *height = 0;
    while ((line = get_next_line(fd)))
    {
        (*height)++;
        free(line);
    }
    close(fd);
    lines = (char **)malloc(sizeof(char *) * (*height + 1));
    return (lines);
}
References get_next_line().
Referenced by read_map().
clean_newline()
static void clean_newline (char * line) static
Definition at line 15 of file map.c.
{
    int len;
    len = ft_strlen(line);
    if (len > 0 && line[len - 1] == '\n')
        line[len - 1] = '\0';
}
Referenced by read_map().
read_map()
char ** read_map (char * file, int * width, int * height)
Reads and parses the game map from a file.
Parameters
file Path to the map file
width Pointer to store map width
height Pointer to store map height
Returns
char** 2D array containing the map data
Reads map file line by line
Allocates memory for map storage
Validates map dimensions
Returns NULL if any error occurs
Definition at line 68 of file map.c.
{
    int     fd;
    char    *line;
    char    **lines;
    int     i;
    lines = allocate_map(file, height);
    if (!lines)
    {
        ft_printf("Error: Cannot open map file\n");
        return (NULL);
    }
    fd = open(file, O_RDONLY);
    i = 0;
    *width = 0;
    while ((line = get_next_line(fd)))
    {
        clean_newline(line);
        lines[i] = line;
        *width = validate_width(lines, i, *width);
        if (*width == 0)
        {
            free_map(lines, i);
            return (NULL);
        }
        i++;
    }
    lines[i] = NULL;
    close(fd);
    return (lines);
}
References allocate_map(), clean_newline(), free_map(), get_next_line(), and validate_width().
Referenced by init_mlx_and_map().
validate_width()
static int validate_width (char ** lines, int i, int width) static
Definition at line 44 of file map.c.
{
    if (i == 0)
        width = ft_strlen(lines[i]);
    else if ((int)ft_strlen(lines[i]) != width)
    {
        ft_printf("Error: Map line %d has different length\n", i + 1);
        return (0);
    }
    return (width);
}
Referenced by read_map().