So_Long: srcs/map_validation.c File Reference
map_validation.c File Reference
#include "so_long.h"
Functions
static char ** copy_map (t_game *game)
static void flood_fill (char **map_copy, int x, int y, t_counts *count)
void free_map (char **map, int height)
Frees the allocated map memory.
int validate_map (t_game *game)
static int validate_path (t_game *game)
Function Documentation
copy_map()
static char ** copy_map (t_game * game) static
Examples
/home/mkurkar/CoreProjects/so_long/srcs/map_validation.c.
Definition at line 32 of file map_validation.c.
{
    char    **map_copy;
    int     i;
    map_copy = (char **)malloc(sizeof(char *) * (game->map_height + 1));
    if (!map_copy)
        return (NULL);
    i = 0;
    while (i < game->map_height)
    {
        map_copy[i] = ft_strdup(game->map[i]);
        if (!map_copy[i])
        {
            free_map(map_copy, i);
            return (NULL);
        }
        i++;
    }
    map_copy[i] = NULL;
    return (map_copy);
}
References free_map().
Referenced by validate_path().
flood_fill()
static void flood_fill (char ** map_copy, int x, int y, t_counts * count) static
Examples
/home/mkurkar/CoreProjects/so_long/srcs/map_validation.c.
Definition at line 15 of file map_validation.c.
{
    if (x < 0 || y < 0 || !map_copy[y] || !map_copy[y][x])
        return ;
    if (map_copy[y][x] == '1' || map_copy[y][x] == 'F')
        return ;
    if (map_copy[y][x] == 'C')
        count->collect--;
    else if (map_copy[y][x] == 'E')
        count->exit = 1;
    map_copy[y][x] = 'F';
    flood_fill(map_copy, x + 1, y, count);
    flood_fill(map_copy, x - 1, y, count);
    flood_fill(map_copy, x, y + 1, count);
    flood_fill(map_copy, x, y - 1, count);
}
References s_counts::collect, s_counts::exit, and flood_fill().
Referenced by flood_fill(), and validate_path().
free_map()
void free_map (char ** map, int height)
Frees the allocated map memory.
Parameters
map 2D array to free
height Number of rows in the map
Examples
/home/mkurkar/CoreProjects/so_long/srcs/map_validation.c.
Definition at line 147 of file map_validation.c.
{
    int i;
    if (!map)
        return ;
    i = 0;
    while (i < height)
    {
        free(map[i]);
        i++;
    }
    free(map);
}
Referenced by copy_map(), reading_map(), and validate_path().
validate_map()
int validate_map (t_game * game)
Examples
/home/mkurkar/CoreProjects/so_long/srcs/map_validation.c.
Definition at line 123 of file map_validation.c.
{
    t_counts    count;
    count = (t_counts){0, 0, 0};
    if (!check_map_borders(game))
        return (0);
    if (!check_map_content(game, &count))
        return (0);
    if (!validate_counts(game, count))
        return (0);
    if (!validate_path(game))
        return (0);
    ft_printf("Map validation successful:\n");
    ft_printf("- Size: %dx%d\n", game->map_width, game->map_height);
    ft_printf("- Collectibles: %d\n", count.collect);
    return (1);
}
References check_map_borders(), check_map_content(), s_counts::collect, validate_counts(), and validate_path().
Referenced by init_mlx_and_map().
validate_path()
static int validate_path (t_game * game) static
Examples
/home/mkurkar/CoreProjects/so_long/srcs/map_validation.c.
Definition at line 55 of file map_validation.c.
{
    char        **map_copy;
    t_counts    count;
    map_copy = copy_map(game);
    if (!map_copy)
        return (0);
    count.collect = game->collectibles_count;
    count.exit = 0;
    flood_fill(map_copy, game->player_x, game->player_y, &count);
    free_map(map_copy, game->map_height);
    if (count.collect > 0)
    {
        ft_printf("Error: Unable to reach all collectibles\n");
        return (0);
    }
    if (!count.exit)
    {
        ft_printf("Error: Unable to reach the exit\n");
        return (0);
    }
    return (1);
}
References s_counts::collect, copy_map(), s_counts::exit, flood_fill(), and free_map().
Referenced by validate_map().