So_Long: srcs/player.c File Reference
player.c File Reference
Player movement and interaction handling.
#include "so_long.h"
Functions
static void handle_collectible (t_game *game)
static void handle_exit (t_game *game)
int key_hook (int keycode, t_game *game)
Handles keyboard input events.
void move_player (t_game *game, int dx, int dy)
Handles player movement and collision.
static void update_player_pos (t_game *game, int new_x, int new_y)
Detailed Description
Player movement and interaction handling.
Definition in file player.c.
Function Documentation
handle_collectible()
static void handle_collectible (t_game * game) static
Definition at line 20 of file player.c.
{
    game->collectibles_count--;
    if (game->collectibles_count == 0)
    {
        game->can_exit = 1;
        ft_printf("All collectibles gathered! Go to exit!\n");
    }
}
Referenced by move_player().
handle_exit()
static void handle_exit (t_game * game) static
Definition at line 30 of file player.c.
{
    if (game->can_exit)
    {
        ft_printf("You won in %d moves!\n", game->moves_count + 1);
        cleanup_game(game);
        exit(0);
    }
}
References cleanup_game().
Referenced by move_player().
key_hook()
int key_hook (int keycode, t_game * game)
Handles keyboard input events.
Parameters
keycode The key code of the pressed key
game Pointer to the game structure
Returns
int Always returns 0
Controls:
ESC (65307): Exits the game
W/Up (13/119): Move up
S/Down (1/115): Move down
A/Left (0/97): Move left
D/Right (2/100): Move right
Definition at line 102 of file player.c.
{
    if (keycode == XK_Escape)
    {
        cleanup_game(game);
        exit(0);
    }
    else if (keycode == XK_w || keycode == XK_Up)
        move_player(game, 0, -1);
    else if (keycode == XK_s || keycode == XK_Down)
        move_player(game, 0, 1);
    else if (keycode == XK_a || keycode == XK_Left)
        move_player(game, -1, 0);
    else if (keycode == XK_d || keycode == XK_Right)
        move_player(game, 1, 0);
    return (0);
}
References cleanup_game(), and move_player().
Referenced by init_game().
move_player()
void move_player (t_game * game, int dx, int dy)
Handles player movement and collision.
Parameters
game Pointer to game structure
dx X-axis movement (-1, 0, 1)
dy Y-axis movement (-1, 0, 1)
Updates player position if move is valid
Handles collectible pickup
Manages exit condition
Updates player direction and animation state
Definition at line 67 of file player.c.
{
    int new_x;
    int new_y;
    new_x = game->player_x + dx;
    new_y = game->player_y + dy;
    if (dx > 0)
        game->facing_right = 1;
    else if (dx < 0)
        game->facing_right = 0;
    if (game->map[new_y][new_x] == '1')
        return ;
    if (game->map[new_y][new_x] == 'C')
        handle_collectible(game);
    if (game->map[new_y][new_x] == 'E')
    {
        handle_exit(game);
    }
    update_player_pos(game, new_x, new_y);
}
References handle_collectible(), handle_exit(), and update_player_pos().
Referenced by key_hook().
update_player_pos()
static void update_player_pos (t_game * game, int new_x, int new_y) static
Definition at line 40 of file player.c.
{
    if (game->player_x == game->exit_x && game->player_y == game->exit_y)
        game->map[game->player_y][game->player_x] = 'E';
    else
        game->map[game->player_y][game->player_x] = '0';
    game->map[new_y][new_x] = 'P';
    game->player_x = new_x;
    game->player_y = new_y;
    game->is_running = 1;
    game->run_counter = 0;
    game->moves_count++;
}
Referenced by move_player().