So_Long: srcs/render_frame.c File Reference
render_frame.c File Reference
#include "so_long.h"
Functions
static void draw_entities (t_game *game)
static void draw_floor_and_exit (t_game *game)
static void draw_player (t_game *game, int x, int y)
int render_frame (t_game *game)
Renders a complete frame of the game.
Function Documentation
draw_entities()
static void draw_entities (t_game * game) static
Definition at line 61 of file render_frame.c.
{
    int i;
    int j;
    int x;
    int y;
    i = 0;
    while (game->map[i])
    {
        j = 0;
        while (game->map[i][j])
        {
            x = j * game->tile_size;
            y = i * game->tile_size;
            if (game->map[i][j] == '1')
                put_img_to_img(&game->buffer, game->wall, x, y);
            else if (game->map[i][j] == 'P')
                draw_player(game, x, y);
            else if (game->map[i][j] == 'C')
                put_img_to_img(&game->buffer, game->collect[game->frame % 8], x,
                    y);
            j++;
        }
        i++;
    }
}
References draw_player(), and put_img_to_img().
Referenced by render_frame().
draw_floor_and_exit()
static void draw_floor_and_exit (t_game * game) static
Definition at line 15 of file render_frame.c.
{
    int i;
    int j;
    int x;
    int y;
    i = 0;
    while (game->map[i])
    {
        j = 0;
        while (game->map[i][j])
        {
            x = j * game->tile_size;
            y = i * game->tile_size;
            put_img_to_img(&game->buffer, game->floor[game->floor_types[i][j]],
                x, y);
            if (game->map[i][j] == 'E' && game->can_exit)
                put_img_to_img(&game->buffer, game->exit, x, y);
            j++;
        }
        i++;
    }
}
References put_img_to_img().
Referenced by render_frame().
draw_player()
static void draw_player (t_game * game, int x, int y) static
Definition at line 40 of file render_frame.c.
{
    void    *sprite;
    if (game->facing_right)
    {
        if (game->is_running)
            sprite = game->player_run[game->frame % 6];
        else
            sprite = game->player_idle[game->frame % 6];
    }
    else
    {
        if (game->is_running)
            sprite = game->player_run_left[game->frame % 6];
        else
            sprite = game->player_idle_left[game->frame % 6];
    }
    put_img_to_img(&game->buffer, sprite, x, y);
}
References put_img_to_img().
Referenced by draw_entities().
render_frame()
int render_frame (t_game * game)
Renders a complete frame of the game.
Parameters
game Pointer to game structure
Returns
int Always returns 0
Rendering order:
Clear buffer
Draw floor tiles
Draw exit
Draw walls
Draw player with direction/animation
Draw collectibles
Draw UI elements
Definition at line 103 of file render_frame.c.
{
    char    moves_str[32];
    ft_memset(game->buffer.addr, 0, game->map_width * game->tile_size
        * game->map_height * game->tile_size * (game->buffer.bpp / 8));
    draw_floor_and_exit(game);
    draw_entities(game);
    mlx_put_image_to_window(game->mlx, game->win, game->buffer.img_ptr, 0, 0);
    ft_snprintf(moves_str, sizeof(moves_str), "Moves: %d", game->moves_count);
    mlx_string_put(game->mlx, game->win, 10, 20, 0xFFFFFF, moves_str);
    return (0);
}
References draw_entities(), draw_floor_and_exit(), and ft_snprintf().
Referenced by animate(), expose_hook(), and main().