So_Long: includes/so_long.h File Reference
so_long.h File Reference
Main header file for the so_long game.
#include <mlx.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <fcntl.h>
#include <string.h>
#include "get_next_line_bonus.h"
#include <stdarg.h>
#include "libft.h"
#include "ft_printf.h"
#include <time.h>
#include <X11/keysym.h>
Classes
struct s_counts
struct s_game
struct s_img
struct s_pos
struct s_win
Typedefs
typedef struct s_counts t_counts
typedef struct s_game t_game
typedef struct s_img t_img
typedef struct s_pos t_pos
typedef struct s_win t_win
Functions
int animate (t_game *game)
Handles game animation frames and state updates.
void cleanup_game (t_game *game)
int close_window (t_game *game)
int expose_hook (t_game *game)
Handles window expose events.
void flip_sprites (t_game *game)
Creates left-facing versions of all player sprites.
void free_map (char **map, int height)
Frees the allocated map memory.
int ft_snprintf (char *str, size_t size, const char *format,...)
Custom implementation of snprintf for integer and string conversion.
void handle_error (t_game *game, const char *message)
void init_buffer (t_game *game)
Initializes the rendering buffer.
void init_collectibles (t_game *game)
Initializes collectible items and exit.
void init_floor_types (t_game *game)
Initializes random floor tile variations.
void init_game (t_game *game, char *map_path)
Main game initialization function.
void init_player_position (t_game *game)
Locates and sets the player's starting position.
int key_hook (int keycode, t_game *game)
Handles keyboard input events.
void load_assets (t_game *game)
Loads all game assets from files.
void load_sprite_array (void *mlx, void **arr, char *base_path, int frames)
Loads a sequence of sprite frames from files.
void move_player (t_game *game, int dx, int dy)
Handles player movement and collision.
void put_img_to_img (t_img *dest, void *sprite_ptr, int dest_x, int dest_y)
char ** read_map (char *file, int *width, int *height)
Reads and parses the game map from a file.
int render_frame (t_game *game)
void * scale_image (void *mlx, void *original, int width, int height, int new_size)
Scales an image to a new size.
int validate_map (t_game *game)
Detailed Description
Main header file for the so_long game.
Author
Your Name
Version
1.0
Contains all structure definitions and function prototypes for the so_long 2D game implementation.
Definition in file so_long.h.
Typedef Documentation
t_counts
typedef struct s_counts t_counts
t_game
typedef struct s_game t_game
t_img
typedef struct s_img t_img
t_pos
typedef struct s_pos t_pos
t_win
typedef struct s_win t_win
Function Documentation
animate()
int animate (t_game * game)
Handles game animation frames and state updates.
Parameters
game Pointer to game structure
Returns
int Always returns 0
Updates animation frames every 100 delay ticks
Manages player running/idle state transitions
Triggers frame rendering
Definition at line 100 of file render.c.
{
    static struct timespec  last_time;
    struct timespec         current_time;
    double                  elapsed;
    clock_gettime(CLOCK_MONOTONIC, &current_time);
    elapsed = (current_time.tv_sec - last_time.tv_sec) * 1000.0
        + (current_time.tv_nsec - last_time.tv_nsec) / 1000000.0;
    if (elapsed >= 100.0 || last_time.tv_sec == 0)
    {
        game->frame = (game->frame + 1) % 6;
        last_time = current_time;
        if (game->is_running)
        {
            game->run_counter++;
            if (game->run_counter >= 20)
            {
                game->is_running = 0;
                game->run_counter = 0;
            }
        }
    }
    render_frame(game);
    return (0);
}
References render_frame().
Referenced by init_game().
cleanup_game()
void cleanup_game (t_game * game)
Definition at line 165 of file utils.c.
{
    if (!game)
        return ;
    if (game->mlx)
    {
        cleanup_mlx_images(game);
        cleanup_window(game);
        cleanup_mlx_ptr(game);
    }
    cleanup_map_data(game);
}
References cleanup_map_data(), cleanup_mlx_images(), cleanup_mlx_ptr(), and cleanup_window().
Referenced by exit_game(), handle_error(), handle_exit(), init_game_window(), init_mlx_and_map(), and key_hook().
close_window()
int close_window (t_game * game)
Definition at line 21 of file main.c.
{
    exit_game(game);
    return (0);
}
References exit_game().
Referenced by main().
expose_hook()
int expose_hook (t_game * game)
Handles window expose events.
Parameters
game Pointer to game structure
Returns
int Result of render_frame
Called when window needs to be redrawn, typically after being uncovered or restored.
Definition at line 238 of file render.c.
{
    return (render_frame(game));
}
References render_frame().
Referenced by init_game().
flip_sprites()
void flip_sprites (t_game * game)
Creates left-facing versions of all player sprites.
Parameters
game Pointer to game structure
Creates mirrored versions of both idle and running animations for the player character. These are used when the player is moving or facing left.
Definition at line 161 of file assets.c.
{
    int i;
    i = 0;
    while (i < 6)
    {
        game->player_idle_left[i] = flip_image_horizontal(game->mlx,
                game->player_idle[i]);
        game->player_run_left[i] = flip_image_horizontal(game->mlx,
                game->player_run[i]);
        i++;
    }
}
References flip_image_horizontal().
Referenced by init_game().
free_map()
void free_map (char ** map, int height)
Frees the allocated map memory.
Parameters
map 2D array to free
height Number of rows in the map
Definition at line 102 of file map_validation.c.
{
    if (!map)
        return ;
    for (int i = 0; i < height; i++)
        free(map[i]);
    free(map);
}
Referenced by read_map().
ft_snprintf()
int ft_snprintf (char * str, size_t size, const char * format, ...)
Custom implementation of snprintf for integer and string conversion.
Parameters
str Output buffer
size Buffer size
format Format string (supports d and s)
... Variable arguments
Returns
Number of characters written (excluding null terminator)
Definition at line 61 of file ft_snprintf.c.
{
    va_list args;
    int     pos;
    if (!str || !format || size == 0)
        return (0);
    va_start(args, format);
    pos = 0;
    while (*format && pos < (int)size - 1)
    {
        if (*format == '%')
        {
            format++;
            if (*format == 'd')
                ft_itoa_to_buf(va_arg(args, int), str, &pos, size);
            else if (*format == 's')
                ft_strncpy_buf(va_arg(args, char *), str, &pos, size);
            format++;
        }
        else
            str[pos++] = *format++;
    }
    str[pos] = '\0';
    va_end(args);
    return (pos);
}
References ft_itoa_to_buf(), and ft_strncpy_buf().
Referenced by load_sprite_array(), and render_frame().
handle_error()
void handle_error (t_game * game, const char * message)
Definition at line 178 of file utils.c.
{
    ft_printf("Error: %s\n", message);
    cleanup_game(game);
    exit(1);
}
References cleanup_game().
Referenced by main().
init_buffer()
void init_buffer (t_game * game)
Initializes the rendering buffer.
Parameters
game Pointer to game structure
Creates an off-screen buffer for rendering the game frame. Buffer size matches the window dimensions. Used for double buffering to prevent flickering.
Definition at line 77 of file render.c.
{
    int win_width;
    int win_height;
    win_width = game->map_width * game->tile_size;
    win_height = game->map_height * game->tile_size;
    game->buffer.img_ptr = mlx_new_image(game->mlx, win_width, win_height);
    game->buffer.addr = mlx_get_data_addr(game->buffer.img_ptr,
            &game->buffer.bpp, &game->buffer.line_len, &game->buffer.endian);
}
Referenced by init_game().
init_collectibles()
void init_collectibles (t_game * game)
Initializes collectible items and exit.
Parameters
game Pointer to game structure
Counts total collectibles ('C' in map)
Locates exit position ('E' in map)
Initializes completion tracking
Definition at line 86 of file init.c.
{
    int i;
    int j;
    i = 0;
    game->collectibles_count = 0;
    while (game->map[i])
    {
        j = 0;
        while (game->map[i][j])
        {
            if (game->map[i][j] == 'C')
                game->collectibles_count++;
            else if (game->map[i][j] == 'E')
            {
                game->exit_x = j;
                game->exit_y = i;
            }
            j++;
        }
        i++;
    }
    game->can_exit = 0;
}
Referenced by init_game().
init_floor_types()
void init_floor_types (t_game * game)
Initializes random floor tile variations.
Parameters
game Pointer to game structure
Creates a 2D array of floor type indices. Each position gets a random floor variant (0-9) for visual variety in the game.
Definition at line 24 of file init.c.
{
    int i;
    int j;
    i = 0;
    game->floor_types = (unsigned char **)malloc(sizeof(unsigned char *)
            * game->map_height);
    while (i < game->map_height)
    {
        j = 0;
        game->floor_types[i] = (unsigned char *)malloc(sizeof(unsigned char)
                * game->map_width);
        while (j < game->map_width)
        {
            game->floor_types[i][j] = (unsigned char)(rand() % 10);
            j++;
        }
        i++;
    }
}
Referenced by load_assets().
init_game()
void init_game (t_game * game, char * map_path)
Main game initialization function.
Parameters
game Pointer to game structure
map_path Path to the map file
Initialization sequence:
Reset game state
Initialize MLX
Load map
Create window
Load assets
Initialize player and collectibles
Set up event hooks
Definition at line 172 of file init.c.
{
    init_game_vars(game);
    init_mlx_and_map(game, map_path);
    init_game_window(game);
    init_buffer(game);
    load_assets(game);
    flip_sprites(game);
    init_player_position(game);
    init_collectibles(game);
    mlx_hook(game->win, 2, 1L << 0, key_hook, game);
    mlx_hook(game->win, 12, 0, expose_hook, game);
    mlx_loop_hook(game->mlx, animate, game);
}
References animate(), expose_hook(), flip_sprites(), init_buffer(), init_collectibles(), init_game_vars(), init_game_window(), init_mlx_and_map(), init_player_position(), key_hook(), and load_assets().
Referenced by main().
init_player_position()
void init_player_position (t_game * game)
Locates and sets the player's starting position.
Parameters
game Pointer to game structure
Scans the map for 'P' character and sets player_x and player_y coordinates accordingly.
Definition at line 54 of file init.c.
{
    int i;
    int j;
    i = 0;
    while (game->map[i])
    {
        j = 0;
        while (game->map[i][j])
        {
            if (game->map[i][j] == 'P')
            {
                game->player_x = j;
                game->player_y = i;
                return ;
            }
            j++;
        }
        i++;
    }
}
Referenced by init_game().
key_hook()
int key_hook (int keycode, t_game * game)
Handles keyboard input events.
Parameters
keycode The key code of the pressed key
game Pointer to the game structure
Returns
int Always returns 0
Controls:
ESC (65307): Exits the game
W/Up (13/119): Move up
S/Down (1/115): Move down
A/Left (0/97): Move left
D/Right (2/100): Move right
Definition at line 102 of file player.c.
{
    if (keycode == XK_Escape)
    {
        cleanup_game(game);
        exit(0);
    }
    else if (keycode == XK_w || keycode == XK_Up)
        move_player(game, 0, -1);
    else if (keycode == XK_s || keycode == XK_Down)
        move_player(game, 0, 1);
    else if (keycode == XK_a|| keycode == XK_Left)
        move_player(game, -1, 0);
    else if (keycode == XK_d || keycode == XK_Right)
        move_player(game, 1, 0);
    return (0);
}
References cleanup_game(), and move_player().
Referenced by init_game().
load_assets()
void load_assets (t_game * game)
Loads all game assets from files.
Parameters
game Pointer to game structure
Loads and initializes:
Floor tiles (10 variants)
Player animations (idle and running)
Collectible items
Wall textures
Exit texture All textures are scaled to match tile_size (32x32)
Definition at line 210 of file assets.c.
{
    game->tile_size = 32;
    game->img_width = game->tile_size;
    game->img_height = game->tile_size;
    ft_printf("Loading assets...\n");
    load_sprite_array(game->mlx, game->floor, "./final_assets/floor", 10);
    load_sprite_array(game->mlx, game->player_idle, "./final_assets/idle_knigh",
        6);
    load_sprite_array(game->mlx, game->player_run, "./final_assets/run_knight",
        6);
    load_sprite_array(game->mlx, game->collect, "./final_assets/chest", 8);
    load_single_texture(game, &game->wall, "./final_assets/wall/f1.xpm");
    load_single_texture(game, &game->exit, "./final_assets/exit.xpm");
    init_floor_types(game);
    ft_printf("All assets loaded successfully!\n");
}
References init_floor_types(), load_single_texture(), and load_sprite_array().
Referenced by init_game().
load_sprite_array()
void load_sprite_array (void * mlx, void ** arr, char * base_path, int frames)
Loads a sequence of sprite frames from files.
Parameters
mlx MLX instance pointer
arr Array to store the loaded sprites
base_path Base path to the sprite files
frames Number of frames to load
Loads a sequence of XPM files named f0.xpm through f{frames-1}.xpm from the specified directory. Each sprite is scaled to 32x32 pixels.
Definition at line 122 of file assets.c.
{
    char    path[256];
    void    *orig_img;
    void    *scaled_img;
    int     params[3];
    int     i;
    i = 0;
    while (i < frames)
    {
        ft_snprintf(path, sizeof(path), "%s/f%d.xpm", base_path, i);
        orig_img = mlx_xpm_file_to_image(mlx, path, &params[0], &params[1]);
        if (!orig_img)
        {
            ft_printf("Error: Failed to load %s\n", path);
            exit(1);
        }
        scaled_img = scale_image(mlx, orig_img, params[0], params[1], 32);
        mlx_destroy_image(mlx, orig_img);
        if (!scaled_img)
        {
            ft_printf("Error: Failed to scale image %s\n", path);
            exit(1);
        }
        arr[i] = scaled_img;
        i++;
    }
}
References ft_snprintf(), and scale_image().
Referenced by load_assets().
move_player()
void move_player (t_game * game, int dx, int dy)
Handles player movement and collision.
Parameters
game Pointer to game structure
dx X-axis movement (-1, 0, 1)
dy Y-axis movement (-1, 0, 1)
Updates player position if move is valid
Handles collectible pickup
Manages exit condition
Updates player direction and animation state
Definition at line 67 of file player.c.
{
    int new_x;
    int new_y;
    new_x = game->player_x + dx;
    new_y = game->player_y + dy;
    if (dx > 0)
        game->facing_right = 1;
    else if (dx < 0)
        game->facing_right = 0;
    if (game->map[new_y][new_x] == '1')
        return ;
    if (game->map[new_y][new_x] == 'C')
        handle_collectible(game);
    if (game->map[new_y][new_x] == 'E')
    {
        handle_exit(game);
    }
    update_player_pos(game, new_x, new_y);
}
References handle_collectible(), handle_exit(), and update_player_pos().
Referenced by key_hook().
put_img_to_img()
void put_img_to_img (t_img * dest, void * sprite_ptr, int dest_x, int dest_y)
Definition at line 45 of file render.c.
{
    t_img  sprite;
    t_pos  pos;
    sprite.img_ptr = sprite_ptr;
    sprite.addr = mlx_get_data_addr(sprite.img_ptr, &sprite.bpp,
            &sprite.line_len, &sprite.endian);
    pos.row = 0;
    pos.dest_x = dest_x;
    pos.dest_y = dest_y;
    while (pos.row < 32)
    {
        pos.col = 0;
        while (pos.col < 32)
        {
            put_img_to_img_part(dest, &sprite, pos);
            pos.col++;
        }
        pos.row++;
    }
}
References s_img::addr, s_img::bpp, s_pos::col, s_pos::dest_x, s_pos::dest_y, s_img::endian, s_img::img_ptr, s_img::line_len, put_img_to_img_part(), and s_pos::row.
Referenced by draw_entities(), draw_floor_and_exit(), and draw_player().
read_map()
char ** read_map (char * file, int * width, int * height)
Reads and parses the game map from a file.
Parameters
file Path to the map file
width Pointer to store map width
height Pointer to store map height
Returns
char** 2D array containing the map data
Reads map file line by line
Allocates memory for map storage
Validates map dimensions
Returns NULL if any error occurs
Definition at line 68 of file map.c.
{
    int     fd;
    char    *line;
    char    **lines;
    int     i;
    lines = allocate_map(file, height);
    if (!lines)
    {
        ft_printf("Error: Cannot open map file\n");
        return (NULL);
    }
    fd = open(file, O_RDONLY);
    i = 0;
    *width = 0;
    while ((line = get_next_line(fd)))
    {
        clean_newline(line);
        lines[i] = line;
        *width = validate_width(lines, i, *width);
        if (*width == 0)
        {
            free_map(lines, i);
            return (NULL);
        }
        i++;
    }
    lines[i] = NULL;
    close(fd);
    return (lines);
}
References allocate_map(), clean_newline(), free_map(), get_next_line(), and validate_width().
Referenced by init_mlx_and_map().
render_frame()
int render_frame (t_game * game)
Definition at line 215 of file render.c.
{
    char    moves_str[32];
    ft_memset(game->buffer.addr, 0, game->map_width * game->tile_size
        * game->map_height * game->tile_size * (game->buffer.bpp / 8));
    draw_floor_and_exit(game);
    draw_entities(game);
    mlx_put_image_to_window(game->mlx, game->win, game->buffer.img_ptr, 0, 0);
    ft_snprintf(moves_str, sizeof(moves_str), "Moves: %d", game->moves_count);
    mlx_string_put(game->mlx, game->win, 10, 20, 0xFFFFFF, moves_str);
    return (0);
}
References draw_entities(), draw_floor_and_exit(), and ft_snprintf().
Referenced by animate(), expose_hook(), and main().
scale_image()
void * scale_image (void * mlx, void * original, int width, int height, int n_size)
Scales an image to a new size.
Parameters
mlx MLX instance pointer
original Original image
width Original width
height Original height
new_size Target size
Returns
void* Scaled image pointer or NULL on failure
Creates a new scaled version of the input image using nearest neighbor interpolation.
Definition at line 34 of file assets.c.
{
    void    *new_img;
    int     *orig_data;
    int     *new_data;
    int     params[5];
    new_img = mlx_new_image(mlx, n_size, n_size);
    if (!new_img)
        return (NULL);
    orig_data = (int *)mlx_get_data_addr(original, &params[0], &params[1],
            &params[2]);
    if (!orig_data)
    {
        mlx_destroy_image(mlx, new_img);
        return (NULL);
    }
    new_data = (int *)mlx_get_data_addr(new_img, &params[0], &params[1],
            &params[2]);
    if (!new_data)
    {
        mlx_destroy_image(mlx, new_img);
        return (NULL);
    }
    params[3] = -1;
    while (++params[3] < n_size)
    {
        params[4] = -1;
        while (++params[4] < n_size)
            if (params[3] * width / n_size * width + params[4] * width
                / n_size >= 0 && params[3] * width / n_size * width + params[4]
                * width / n_size < (width * height))
                new_data[params[3] * n_size + params[4]] = orig_data[params[3]
                    * width / n_size * width + params[4] * width / n_size];
    }
    return (new_img);
}
Referenced by load_single_texture(), and load_sprite_array().
validate_map()
int validate_map (t_game * game)
Definition at line 68 of file map_validation.c.
{
    t_counts    count;
    int         i;
    int         j;
    count = (t_counts){0, 0, 0};
    if (!check_map_borders(game))
        return (0);
    i = -1;
    while (++i < game->map_height)
    {
        if ((int)ft_strlen(game->map[i]) != game->map_width)
            return (ft_printf("Error: Map not rectangular\n") && 0);
        if (game->map[i][0] != '1' || game->map[i][game->map_width - 1] != '1')
            return (ft_printf("Error: Map not surrounded by walls\n") && 0);
        j = -1;
        while (++j < game->map_width)
            if (!check_elements(game, i, j, &count))
                return (0);
    }
    if (!validate_counts(game, count))
        return (0);
    ft_printf("Map validation successful:\n");
    ft_printf("- Size: %dx%d\n", game->map_width, game->map_height);
    ft_printf("- Collectibles: %d\n", count.collect);
    return (1);
}
References check_elements(), check_map_borders(), s_counts::collect, and validate_counts().
Referenced by init_mlx_and_map().