So_Long: srcs/utils.c File Reference
utils.c File Reference
#include "so_long.h"
Functions
static void cleanup_collect_anims (t_game *game)
static void cleanup_floor_images (t_game *game)
void cleanup_game (t_game *game)
static void cleanup_map_data (t_game *game)
static void cleanup_mlx_images (t_game *game)
static void cleanup_mlx_ptr (t_game *game)
static void cleanup_player_anims (t_game *game)
static void cleanup_player_left_anims (t_game *game)
static void cleanup_scaled_images (t_game *game)
static void cleanup_window (t_game *game)
void handle_error (t_game *game, const char *message)
Function Documentation
cleanup_collect_anims()
static void cleanup_collect_anims (t_game * game) static
Definition at line 83 of file utils.c.
{
    int i;
    i = 0;
    while (i < 8)
    {
        if (game->collect[i])
        {
            mlx_destroy_image(game->mlx, game->collect[i]);
            game->collect[i] = NULL;
        }
        i++;
    }
}
Referenced by cleanup_scaled_images().
cleanup_floor_images()
static void cleanup_floor_images (t_game * game) static
Definition at line 25 of file utils.c.
{
    int i;
    i = 0;
    while (i < 10)
    {
        if (game->floor[i])
        {
            mlx_destroy_image(game->mlx, game->floor[i]);
            game->floor[i] = NULL;
        }
        i++;
    }
}
Referenced by cleanup_scaled_images().
cleanup_game()
void cleanup_game (t_game * game)
Definition at line 165 of file utils.c.
{
    if (!game)
        return ;
    if (game->mlx)
    {
        cleanup_mlx_images(game);
        cleanup_window(game);
        cleanup_mlx_ptr(game);
    }
    cleanup_map_data(game);
}
References cleanup_map_data(), cleanup_mlx_images(), cleanup_mlx_ptr(), and cleanup_window().
Referenced by exit_game(), handle_error(), handle_exit(), init_game_window(), init_mlx_and_map(), and key_hook().
cleanup_map_data()
static void cleanup_map_data (t_game * game) static
Definition at line 137 of file utils.c.
{
    int i;
    if (game->map)
    {
        i = 0;
        while (i < game->map_height)
        {
            free(game->map[i]);
            i++;
        }
        free(game->map);
        game->map = NULL;
    }
    if (game->floor_types)
    {
        i = 0;
        while (i < game->map_height)
        {
            free(game->floor_types[i]);
            i++;
        }
        free(game->floor_types);
        game->floor_types = NULL;
    }
}
Referenced by cleanup_game().
cleanup_mlx_images()
static void cleanup_mlx_images (t_game * game) static
Definition at line 107 of file utils.c.
{
    if (game->buffer.img_ptr)
    {
        mlx_destroy_image(game->mlx, game->buffer.img_ptr);
        game->buffer.img_ptr = NULL;
    }
    cleanup_scaled_images(game);
    if (game->wall)
    {
        mlx_destroy_image(game->mlx, game->wall);
        game->wall = NULL;
    }
    if (game->exit)
    {
        mlx_destroy_image(game->mlx, game->exit);
        game->exit = NULL;
    }
}
References cleanup_scaled_images().
Referenced by cleanup_game().
cleanup_mlx_ptr()
static void cleanup_mlx_ptr (t_game * game) static
Definition at line 15 of file utils.c.
{
    if (game->mlx)
    {
        mlx_destroy_display(game->mlx);
        free(game->mlx);
        game->mlx = NULL;
    }
}
Referenced by cleanup_game().
cleanup_player_anims()
static void cleanup_player_anims (t_game * game) static
Definition at line 41 of file utils.c.
{
    int i;
    i = 0;
    while (i < 6)
    {
        if (game->player_idle[i])
        {
            mlx_destroy_image(game->mlx, game->player_idle[i]);
            game->player_idle[i] = NULL;
        }
        if (game->player_run[i])
        {
            mlx_destroy_image(game->mlx, game->player_run[i]);
            game->player_run[i] = NULL;
        }
        i++;
    }
}
Referenced by cleanup_scaled_images().
cleanup_player_left_anims()
static void cleanup_player_left_anims (t_game * game) static
Definition at line 62 of file utils.c.
{
    int i;
    i = 0;
    while (i < 6)
    {
        if (game->player_idle_left[i])
        {
            mlx_destroy_image(game->mlx, game->player_idle_left[i]);
            game->player_idle_left[i] = NULL;
        }
        if (game->player_run_left[i])
        {
            mlx_destroy_image(game->mlx, game->player_run_left[i]);
            game->player_run_left[i] = NULL;
        }
        i++;
    }
}
Referenced by cleanup_scaled_images().
cleanup_scaled_images()
static void cleanup_scaled_images (t_game * game) static
Definition at line 99 of file utils.c.
{
    cleanup_floor_images(game);
    cleanup_player_anims(game);
    cleanup_player_left_anims(game);
    cleanup_collect_anims(game);
}
References cleanup_collect_anims(), cleanup_floor_images(), cleanup_player_anims(), and cleanup_player_left_anims().
Referenced by cleanup_mlx_images().
cleanup_window()
static void cleanup_window (t_game * game) static
Definition at line 127 of file utils.c.
{
    if (game->win)
    {
        mlx_clear_window(game->mlx, game->win);
        mlx_destroy_window(game->mlx, game->win);
        game->win = NULL;
    }
}
Referenced by cleanup_game().
handle_error()
void handle_error (t_game * game, const char * message)
Definition at line 178 of file utils.c.
{
    ft_printf("Error: %s\n", message);
    cleanup_game(game);
    exit(1);
}
References cleanup_game().
Referenced by main().